### ISSUE TITLE
The story module failed to run.

### ISSUE THREAD

**Issue by SupreCyk** [EMNLP-2024-CritiCS/Collective-Critics-for-Creative-Story-Generation#1]
Dear Author,

I have read your article and tried running your code. The plan module works fine, but I keep encountering failures when running the story module. May I ask if you made any modifications based on the DOC Story Generation V2 code when running it?

Best regards！

**Comment by wuhongyan123** [comment]
Hello, I would like to ask how to change the host and port field in the config.yaml file if the openai api is not involved.
